global:
  message: Welcome to order service dev environment!!
server:
  port: 1002
message: Hello from Dev!
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/order_master?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
     username: root
     password: Netid$3776
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
